### ISSUE TITLE
docker run 后面提示的镜像名会带一大串空格

### ISSUE THREAD

**Issue by chenbihao** [fenixsoft/fenix-cli#1]
RT：
![image](https://user-images.githubusercontent.com/21167262/124233950-fc79d000-db45-11eb-81ec-afc3d7d4cb09.png)

**Comment by fenixsoft** [comment]
刚刚更新了v1.1.20210702解决此问题。
请运行以下命令自动升级以下即可：`curl -sL https://icyfenix.cn/fenix-cli/dl.sh | sh -`
